version: '3.3'
services:
    freenom:
        ports:
            - '80:80'
        container_name: freenom
        restart: always
        volumes:
            #- './.env:/app/.env.example:ro'
            - './logs:/app/logs'
        environment:
            #Main(Must)
            - FF_TOKEN=12345
            - SHOW_SERVER_INFO=1
            - MOSAIC_SENSITIVE_INFO=1
            - FREENOM_USERNAME=
            - FREENOM_PASSWORD=
            #TelegramBot(Options)
            - TELEGRAM_CHAT_ID=
            - TELEGRAM_BOT_TOKEN=
            - TELEGRAM_BOT_ENABLE=1
            #Mail(Options)
            - MAIL_ENABLE=1
            - MAIL_USERNAME=
            - MAIL_PASSWORD=
            - TO=
            #Custom Mail Server (Options)
            - MAIL_HOST=
            - MAIL_PORT=
            - MAIL_ENCRYPTION=starttls
            #Another (Options)
            - DEBUG=0
            - CUSTOM_LANGUAGE=zh
        image: luolongfei/freenom:koyeb