version: '3.3'
services:
    mariadb:
        container_name: mariadb
        image: 'mariadb:latest'
        environment:
            - MARIADB_USER=admin
            - MARIADB_PASSWORD=admin
            - MARIADB_ROOT_PASSWORD=root
        volumes:
            - './mariadb:/var/lib/mysql'
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        depends_on:
            - mariadb
        ports:
            - '8080:80'
