version: '3.8'
services:
  DiscordGSM:
    container_name: DiscordGSM
    image: chongzhijie/discordgsm:2.9.1
    command: /bin/sh -c "gunicorn --bind 0.0.0.0:8000 --workers=2 --worker-class=gthread app:app --timeout 90 & python -u main.py"
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: always
    volumes :
      - ./data:/usr/src/app/data