version: "3.8"
services:
  AllTube-Download-yt-dlp:
    image: kelvinchin12070811/alltube:3.0.3
    container_name: AllTube-Download
    volumes:
      - ./AllTube-Download/config.yml:/var/www/html/config/config.yml:ro
    ports:
      - 80:80
    networks:
        vlan-net:
            ipv4_address: 192.168.1.69
  
  DrawIO:
    image: jgraph/drawio
    container_name: DrawIO
    environment:
      - LETS_ENCRYPT_ENABLED=false
      - PUBLIC_DNS=
      - ORGANISATION_UNIT=
      - ORGANISATION=
      - CITY=
      - STATE=
      - COUNTRY_CODE=MY
      - KEYSTORE_PASS=
      - KEY_PASS=
    ports:
      - 80:3000
    networks:
        vlan-net:
            ipv4_address: 192.168.1.9

  Librespeed:
    image: linuxserver/librespeed:latest
    container_name: Librespeed
    environment:
      - PASSWORD=
      - CUSTOM_RESULTS=
      - DB_TYPE=mysql
      - DB_HOSTNAME=192.168.1.54
      - DB_NAME=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_PORT=3306
      - PUID=99
      - PGID=100
      - UMASK=022
    volumes:
      - ./Librespeed:/config
    ports:
      - 80:80
    networks:
        vlan-net:
            ipv4_address: 192.168.1.56

  Nextcloud:
    image: linuxserver/nextcloud
    container_name: Nextcloud
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
    volumes:
      - ./Nextcloud:/config
      - /mnt/user/Nextcloud/:/data
    ports:
      - 80:80
      - 443:443
    networks:
        vlan-net:
            ipv4_address: 192.168.1.4
    deploy:
        resources:
            limits:
              cpus: 0,1,2,3,4,5,6,7
    restart: unless-stopped
  
  Typecho:
    image: 80x86/typecho  
    container_name: Typecho
    environment:
      - PUID=1000
      - PGID=1000
      - HTTPD_USER=www
      - PHP_TZ=Asia/Shanghai
      - PHP_MAX_EXECUTION_TIME=600
      - PHP_FPM_MAX_CHILDREN=128
    volumes:
      - ./Typecho:/data
    ports:
      - 80:80
    networks:
        vlan-net:
            ipv4_address: 192.168.1.8
    deploy:
        resources:
            limits:
              cpus: 0,1,2,3,4,5,6,7
  
  UptimeKuma:
    image: louislam/uptime-kuma
    container_name: UptimeKuma
    volumes:
      - ./UptimeKuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
        vlan-net:
            ipv4_address: 192.168.1.6
    deploy:
        resources:
            limits:
              cpus: 0,1,2,3,4,5,6,7
  
  YOURLS:
    image: yourls
    container_name: YOURLS
    environment:
      - YOURLS_SITE=https://your.domain.net/
      - YOURLS_DB_HOST=
      - YOURLS_DB_PASS=
      - YOURLS_DB_NAME=
      - YOURLS_HOURS_OFFSET=0
      - YOURLS_PRIVATE=true
      - YOURLS_USER=
      - YOURLS_PASS=
    ports:
      - 80:80
    networks:
        vlan-net:
            ipv4_address: 192.168.1.5

networks:
  vlan-net:
    name: br0.10
    driver: macvlan
    driver_opts:
      parent: eth0