version: "3.8"
services:
  Heimdall:
    image: linuxserver/heimdall:latest
    container_name: Heimdall
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
    volumes:
      - ./Heimdall:/config
    ports:
      - 80:80
      - 443:443
    networks:
      vlan-net:
        ipv4_address: 192.168.1.71

  NginxProxyManager:
    image: jlesage/nginx-proxy-manager
    container_name: NginxProxyManager
    environment:
      - USER_ID=99
      - GROUP_ID=100
      - UMASK=000
      - DISABLE_IPV6=0
    volumes:
      - ./NginxProxyManager:/config
    ports:
      - 8181:8181
      - 8080:8080
      - 4443:4443
    networks:
      vlan-net:
        ipv4_address: 192.168.1.51

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    environment:
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - PMA_HOST=
      - PMA_PORT=3306
    ports:
      - 80:80
    networks:
      vlan-net:
        ipv4_address: 192.168.1.55

  Portainer-CE:
    image: portainer/portainer-ce
    container_name: Portainer-CE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Portainer-CE:/data
    ports:
      - 80:9000
      - 8000:8000
    networks:
      vlan-net:
        ipv4_address: 192.168.1.52

networks:
  vlan-net:
    name: br0.10
    driver: macvlan
    driver_opts:
      parent: eth0
