version: '3.8'
services:
  DiscordGSM:
    container_name: DiscordGSM
    image: discordgsm/discord-game-server-monitor:latest
    command: /bin/sh -c "gunicorn --bind 0.0.0.0:8000 --workers=2 --worker-class=gthread app:app --timeout 90 & python -u main.py"
    env_file:
      - ./DiscordGSM/.env
    volumes:
      - ./DiscordGSM/data:/usr/src/app/data
    ports:
      - 8000:8000
    networks:
      vlan-net:
        ipv4_address: 192.168.1.63
    restart: always

  Lavalink:
    image: fredboat/lavalink:e892afe
    container_name: Lavalink
    volumes:
      - ./Lavalink/application.yml:/opt/Lavalink/application.yml:ro
    ports:
      - 2333:2333
    networks:
      vlan-net:
        ipv4_address: 192.168.1.57
    restart: unless-stopped

  Sudhanplayz-Discord-Musicbot-v5:
    image: dumplingmiku/sudhanplayz-discord-musicbot-v5:latest
    container_name: Sudhanplayz-Discord-Musicbot-v5
    environment:
      #ip=your lavalink ip default:lavalink.oops.wtf
      - ip=lavalink
      #port=your lavalink port default:2000
      - port=2333
    volumes:
      - ./Sudhanplayz-Discord-Musicbot-v5/config.js:/usr/src/app/config.js:ro
    networks:
      vlan-net:
        ipv4_address: 192.168.1.58
    restart: unless-stopped
  
  DiscordRSS-redis:
    container_name: DiscordRSS-redis
    restart: on-failure:5
    image: redis:alpine
    networks:
        vlan-net:
            ipv4_address: 192.168.1.64

  DiscordRSS-mongodb:
    container_name: DiscordRSS-mongodb
    restart: on-failure:5
    command: mongod --port 27017
    image: mongo:4.4-rc
    volumes:
      - 'db-data:/data/db'
      - './db:/data/db:rw'
    networks:
        vlan-net:
            ipv4_address: 192.168.1.65

  DiscordRSS-bot:
    container_name: DiscordRSS-web-bot
    restart: on-failure:3
    image: synzen/monitorss
    depends_on:
      - DiscordRSS-mongodb
    environment:
      - DRSS_START=bot
      - DRSS_BOT_TOKEN=
      - DRSS_DATABASE_URI=mongodb://192.168.1.65:27017/rss
    networks:
        vlan-net:
            ipv4_address: 192.168.1.66

  DiscordRSS-web:
    container_name: DiscordRSS-web
    image: synzen/monitorss
    restart: on-failure:3
    depends_on:
      - DiscordRSS-redis
      - DiscordRSS-mongodb
    ports:
      - "8081:8081"
    environment:
      - DRSS_START=web
      - DRSSWEB_BOT_TOKEN=
      - DRSSWEB_DATABASE_REDIS=redis://192.168.1.64:6379
      - DRSSWEB_DATABASE_URI=mongodb://192.168.1.65:27017/rss
      - DRSSWEB_BOT_REDIRECTURI=
      - DRSSWEB_BOT_CLIENTID=
      - DRSSWEB_BOT_CLIENTSECRET=
    networks:
        vlan-net:
            ipv4_address: 192.168.1.67
volumes:
  db-data:

networks:
  vlan-net:
    name: br0.10
    driver: macvlan
    driver_opts:
      parent: eth0